version: "3"

services:
  dbserver:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABSE: receipt
      MYSQL_ROOT_PASSWORD: password
    hostname: dbserver

  app:
    build: .
    ports:
      - "8080:8080"
    links:
      - dbserver
    environment:
      MYSQL_USER: root
      MYSQL_PASS: password
      MYSQL_DBNAME: receipt
      MYSQL_IP: abc
    command: go run /go/src/app/interface/slack/main/main_slack.go
