version: "3"

services:
  dbserver:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: receipt
    hostname: dbserver
    volumes:
      - ./db/mysql_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "8080:8080"
    links:
      - dbserver
    environment:
      MYSQL_USER: root
      MYSQL_PASS: password
      MYSQL_DBNAME: receipt
      MYSQL_IP: dbserver:3306
    entrypoint:
      - dockerize
      - -timeout
      - 60s
      - -wait
      - tcp://dbserver:3306
    command: go run /go/src/app/interface/slack/main/main_slack.go
