version: '2'

services:
  dbserver:
    image: mysql:5.7
    cpu_shares: 200
    mem_limit: 134217728
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: receipt
    hostname: dbserver
    volumes:
      - /var/lib/mysql

  app:
    build: .
    cpu_shares: 200
    mem_limit: 134217728
    ports:
      - "8080:8080"
    links:
      - dbserver
    environment:
      MYSQL_USER: root
      MYSQL_PASS: password
      MYSQL_DBNAME: receipt
      MYSQL_IP: dbserver:3306
      Slack_Token: ${Slack_Token}
    entrypoint:
      - dockerize
      - -timeout
      - 60s
      - -wait
      - tcp://dbserver:3306
    command: ./main_slack
