# Golang CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
        environment:
        - MYSQL_USER=root
        - MYSQL_PASS=test
        - MYSQL_DBNAME=test
        - DB_HOST=127.0.0.1
        - DB_PORT=3306
      - image: circleci/mysql:5.7
        environment:
        - MYSQL_ROOT_PASSWORD=test
        - MYSQL_DATABASE=test
        command: [--character-set-server=utf8, --collation-server=utf8_general_ci, --default-storage-engine=innodb]


    working_directory: /go/src/github.com/hikaru7719/receipt-rest-api
    steps:
      - checkout

      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 3m

      - run:
          name: Install dep
          command: go get -u github.com/golang/dep/cmd/dep

      - restore_cache:
          keys:
            - dep-cache-{{.Branch}}-{{checksum "Gopkg.lock"}}

      - run:
          name: Install dependencies
          command: dep ensure

      - store_cache:
          key: dep-cache-{{.Branch}}-{{checksum "Gopkg.lock"}}
          paths: /go/src/github.com/hikaru7719/receipt-rest-api/vendor

      - run:
          name: Define schema
          command: go run /go/src/github.com/hikaru7719/receipt-rest-api/cmd/db_migration.go

      - run:
          name: test
          command: go test -cover ./...